name: terator
description: Template Surat Generator.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  delta_to_html: ^0.2.1
  flutter_html_to_pdf: ^0.7.0
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  html_editor_enhanced: ^2.5.0
  fluttertoast: ^8.1.1
  loading_animation_widget: ^1.2.0+3
  overlay_loading_progress: ^1.0.0
  cached_network_image: ^3.2.3
  google_fonts: ^3.0.1
  intl: ^0.17.0
  sqflite: ^2.2.1
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  cool_alert: ^1.1.0
  url_launcher: ^6.1.7
  flutter_signature_view: ^2.0.0
  document_file_save_plus: ^1.0.9
  share_plus: ^4.0.9
  google_mobile_ads: ^2.3.0
  in_app_update: ^4.0.1
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/empty.png
    - assets/img/file-empty.png
    - assets/img/account-empty.png
    - assets/img/banner.jpg
    - assets/img/terator_logo.png
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
